### ISSUE TITLE
Report metrics

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/stackdriver-reverse-proxy#5]
The proxy can optionally report metrics to the Stackdriver Monitoring about the inflight HTTP requests. Some examples of metrics to provide:
- total number of in-flight requests
- rate of 5xx responses in the last min
- rate of 4xx responses in the last min
- average response time in the last min
- average response size in the last min

/cc @odeke-em

**Comment by odeke-em** [comment]
Awesome feature request.

Just for being verbose and for rough design:
a) Metric reporting should be toggleable behavior e.g with a flag `--track-metrics`
b) By default sampling time for responses is 1min, perhaps could be dynamically set when starting the program `--metric-sample-time` as a duration e.g `--metric-sample-time=30s`.
c) Inside `(*transport) RoundTrip` add the logic in there to capture the metrics
d) A global metrics receiver that collects metrics and after every period from b) fires off a goroutine to report the metrics within that time period e.g

### Rough code
```go
type event struct {
   StatusCode int `json:"code"`
   Request bool `json:"is_req"`
   StartTime int64 `json:"start"`
   EndTime int64 `json:"end"`
}

type metricsReporter struct {
   recvChan chan *event 
   period time.Duration
   mc *monitoring.MetricClient
   blockChan chan bool
}

func newMetricsReporter(ctx context.Context, period time.Duration) (*metricsReporter, error) {
   mc, err := monitoring.NewMetricClient(ctx)
   if err != nil {
      return nil, err
   }
   mr := &metricsReport{
     period: period,
     mc: mc,
     blockChan: make(chan bool, 1),
     recvChan: make(chan *event),
  }
  return mr, nil
}

func (mr *metricsReporter) addEvent(evt *event) {
   mr.block()
   mr.recvChan <- evt
   mr.unblock()
}

func (mr *metricsReporter) do() {
  startTime := time.Now()
  i := uint64(0)
   for  {
       i += 1
       <-time.After(mr.period)
       mr.block()
       drainedEvents := mr.drainEvents()
       mr.unblock()
       go mr.reportEvents(drainedEvents, startTime, time.Now(), i)
   }
}

func (mr *metricsReporter) block() { <-mr.blockChan }
func (mr *metricsReporter) unblock() { mr.blockChan <- true }

func (mr *metricsReporter) reportEvents(events []*event, startTime, endTime time.Time, n uint64) {
  // Do the reporting with mr.mc and calculate the respective metrics
}
```

**Comment by odeke-em** [comment]
Not yet complete.  I used `Updates #8` but that still closed it, hmm. Part 2 to perform the uploads si remaining.

**Comment by rakyll** [comment]
I will work on this later this week.

**Comment by rakyll** [comment]
Closed via https://github.com/GoogleCloudPlatform/stackdriver-reverse-proxy/commit/f9a058107a7ee4a2ca35be36f2602d83fb666949.

**Comment by odeke-em** [comment]
Awesome, ahaha very very similar ideas independently of OpenCensus, great to see this finally closed.
